### PR TITLE
#376 - Fix security vulnerability in glob-parent

### PR DESCRIPTION
**Pull request by pgillislb**
### What is the purpose of this pull request?
Update the version of glob-parent to resolve security vulnerability

### What changes did you make? (Give an overview)
There are no functional changes here, just a dependency update

### CODE REVIEW

**Comment by alexgleason** [comment]
@mrmlnc Plz merge this, copy-webpack-plugin depends on it so multiple steps are needed to get this out of our vulnerability reports.

image

**Comment by nutkur** [comment]
Thank you @alexgleason and @pgillislb for this PR. @mrmlnc can we get this merged sooner? The vulnerability reports are blocking our release

**Comment by johndiiorio** [comment]
@pgillislb @alexgleason @nutkur `glob-parent@5.1.2` is not vulnerable, see #368. This should not be merged.

**Comment by alexgleason** [comment]
@johndiiorio Thank you. That was enlightening!

**Comment by mrmlnc** [comment]
@johndiiorio Thank you!

I do not plan to merge this PR, as it is not a real vulnerability, but a problem in eat another security scanner.

This dependency will be updated in the next major version of the package (#371).

**Pull request closed without merging**
