### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by nicholasostman**
Update glob-parent to avoid package vulnerability. https://github.com/mrmlnc/fast-glob/issues/304#issuecomment-766572086

### CODE REVIEW

**Review by hamzanajeeb-tp — APPROVED** [review]

**Comment by nicholasostman** [comment]
@hamzanajeeb-tp  someone also needs to merge, thanks for the review

**Comment by hamzanajeeb-tp** [comment]
> @hamzanajeeb-tp someone also needs to merge, thanks for the review

I do not have, or know anyone who has, merge rights to this repo.

**Review by LeviSeek — APPROVED** [review]

**Comment by runk** [comment]
@mrmlnc any chance this can be merged & released please? 

It's causing fair bit of trouble given the vulnerabilities with glob-parent@5.1.0

**Comment by mrmlnc** [comment]
I close this PR in favor of #315 because it uses a template.

**Pull request closed without merging**
