### PR TITLE
Fixes #121

### LINKED ISSUE #121: markDirectories doesn't work with absolute:true given a relative path
### Actual behavior
markDirectories does not work when the glob is a relative path and absolute is set to true. Digging into the code it looks like the order of operations of ` Reader.prototype.transform` is incorrect causing it to undo the marked directories/

```
/full/path/test/things/a
/full/path/test/things/b
/full/path/test/things/c
```

### Expected behavior
```
/full/path/test/things/a/
/full/path/test/things/b/
/full/path/test/things/c/
```

### Code sample

```js
import fglob from 'fast-glob'; 

const relativeGlob = 'test/fixtures/*/';

async function test() {
	const list = await fglob(relativeGlob, { absolute : true, onlyDirectories: true, markDirectories:true });

	console.info(list);
}

test();
```

### PR DESCRIPTION
**Pull request by rijnhard**
### What is the purpose of this pull request?
Fixes https://github.com/mrmlnc/fast-glob/issues/121

### What changes did you make? (Give an overview)
*changed order of operations when mixing absolute and markDirectories 
*added tests

### CODE REVIEW

**Comment by rijnhard** [comment]
@mrmlnc done :)

**Comment by mrmlnc** [comment]
Thanks for your work 🌮

**Comment by rijnhard** [comment]
@mrmlnc no thank you for being an active maintainer! It was a pleasure to make a PR

**Comment by mrmlnc** [comment]
I'll release a new version this weekend.

**Pull request merged**
